### PR TITLE
Set $settings['config_sync_directory'] only if it's empty.

### LINKED ISSUE #24: settings.pantheon.php should only set $settings['config_sync_directory'] if it is unset
Currently, the provided `settings.pantheon.php` overrides `$settings['config_sync_directory']` no matter what.

We're using the BLT-provided "settings.php parts" that configure the config directory according to `blt.yml` config file before `settings.pantheon.php` gets included.

I'd suggest we just wrap this with a `if (empty($settings['config_sync_directory']))`.

### PR DESCRIPTION
**Pull request by morvans**
Fixes #24

### CODE REVIEW

**Review by rwagner00 — APPROVED** [review]
Lgtm

**Review by namespacebrian — APPROVED** [review]
The expectation is generally that `settings.pantheon.php` be included first and overridden afterwards, but I see no harm in wrapping this in an empty check.

**Comment by greg-1-anderson** [comment]
This should be backported to 9.x and 8.x and tagged.

**Comment by jspellman814** [comment]
I backported this to [9.x](https://github.com/pantheon-systems/drupal-integrations/pull/26) and [8.x](https://github.com/pantheon-systems/drupal-integrations/pull/27).

**Pull request merged**
